//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.CategoryOfNews = new HashSet<CategoryOfNews>();
        }
    
        public int Id_news { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string TextContent { get; set; }
        public Nullable<int> RefIdRest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOfNews> CategoryOfNews { get; set; }
        public virtual Restorans Restorans { get; set; }
    }
}
