//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int Id_phone { get; set; }
        public string PublicPhone { get; set; }
    }
}
